/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.caricah.iotracah.bootstrap.data.models.users;

import java.io.*;

/**
 * IotUserKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 02/23/2016.
 */
public class IotAccountKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for username. */
    private String username;

    /** Value for partitionId. */
    private String partitionId;

    /**
     * Gets username.
     *
     * @return Value for username.
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets username.
     *
     * @param username New value for username.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Gets partitionId.
     *
     * @return Value for partitionId.
     */
    public String getPartitionId() {
        return partitionId;
    }

    /**
     * Sets partitionId.
     *
     * @param partitionId New value for partitionId.
     */
    public void setPartitionId(String partitionId) {
        this.partitionId = partitionId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof IotAccountKey))
            return false;

        IotAccountKey that = (IotAccountKey)o;

        if (username != null ? !username.equals(that.username) : that.username != null)
            return false;

        if (partitionId != null ? !partitionId.equals(that.partitionId) : that.partitionId != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = username != null ? username.hashCode() : 0;

        res = 31 * res + (partitionId != null ? partitionId.hashCode() : 0);

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "IotUserKey [username=" + username +
            ", partitionId=" + partitionId +
            "]";
    }
}

