/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.caricah.iotracah.bootstrap.data.models.retained;

import java.io.*;

/**
 * IotMessageRetainedKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 02/24/2016.
 */
public class IotMessageRetainedKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for partitionId. */
    private String partitionId;

    /** Value for subscriptionFilterId. */
    private long subscriptionFilterId;

    /**
     * Gets partitionId.
     *
     * @return Value for partitionId.
     */
    public String getPartitionId() {
        return partitionId;
    }

    /**
     * Sets partitionId.
     *
     * @param partitionId New value for partitionId.
     */
    public void setPartitionId(String partitionId) {
        this.partitionId = partitionId;
    }

    /**
     * Gets subscriptionFilterId.
     *
     * @return Value for subscriptionFilterId.
     */
    public long getSubscriptionFilterId() {
        return subscriptionFilterId;
    }

    /**
     * Sets subscriptionFilterId.
     *
     * @param subscriptionFilterId New value for subscriptionFilterId.
     */
    public void setSubscriptionFilterId(long subscriptionFilterId) {
        this.subscriptionFilterId = subscriptionFilterId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof IotMessageRetainedKey))
            return false;

        IotMessageRetainedKey that = (IotMessageRetainedKey)o;

        if (partitionId != null ? !partitionId.equals(that.partitionId) : that.partitionId != null)
            return false;

        if (subscriptionFilterId != that.subscriptionFilterId)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = partitionId != null ? partitionId.hashCode() : 0;

        res = 31 * res + (int)(subscriptionFilterId ^ (subscriptionFilterId >>> 32));

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "IotMessageRetainedKey [partitionId=" + partitionId +
            ", subscriptionFilterId=" + subscriptionFilterId +
            "]";
    }
}

