/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.caricah.iotracah.bootstrap.data.models.retained;

import java.io.*;
import java.util.Objects;

/**
 * IotMessageRetained definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 02/24/2016.
 */
public class IotMessageRetained implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for dateCreated. */
    private java.sql.Timestamp dateCreated;

    /** Value for dateModified. */
    private java.sql.Timestamp dateModified;

    /** Value for isActive. */
    private boolean isActive;

    /** Value for id. */
    private long id;

    /** Value for partitionId. */
    private String partitionId;

    /** Value for subscriptionFilterId. */
    private long subscriptionFilterId;

    /** Value for payload. */
    private Object payload;

    /** Value for qos. */
    private int qos;

    /**
     * Gets dateCreated.
     *
     * @return Value for dateCreated.
     */
    public java.sql.Timestamp getDateCreated() {
        return dateCreated;
    }

    /**
     * Sets dateCreated.
     *
     * @param dateCreated New value for dateCreated.
     */
    public void setDateCreated(java.sql.Timestamp dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * Gets dateModified.
     *
     * @return Value for dateModified.
     */
    public java.sql.Timestamp getDateModified() {
        return dateModified;
    }

    /**
     * Sets dateModified.
     *
     * @param dateModified New value for dateModified.
     */
    public void setDateModified(java.sql.Timestamp dateModified) {
        this.dateModified = dateModified;
    }

    /**
     * Gets isActive.
     *
     * @return Value for isActive.
     */
    public boolean getIsActive() {
        return isActive;
    }

    /**
     * Sets isActive.
     *
     * @param isActive New value for isActive.
     */
    public void setIsActive(boolean isActive) {
        this.isActive = isActive;
    }

    /**
     * Gets id.
     *
     * @return Value for id.
     */
    public long getId() {
        return id;
    }

    /**
     * Sets id.
     *
     * @param id New value for id.
     */
    public void setId(long id) {
        this.id = id;
    }


    public Object getPayload() {
        return payload;
    }

    public void setPayload(Object payload) {
        this.payload = payload;
    }

    public int getQos() {
        return qos;
    }

    public void setQos(int qos) {
        this.qos = qos;
    }

    /**
     * Gets partitionId.
     *
     * @return Value for partitionId.
     */
    public String getPartitionId() {
        return partitionId;
    }

    /**
     * Sets partitionId.
     *
     * @param partitionId New value for partitionId.
     */
    public void setPartitionId(String partitionId) {
        this.partitionId = partitionId;
    }

    /**
     * Gets subscriptionFilterId.
     *
     * @return Value for subscriptionFilterId.
     */
    public long getSubscriptionFilterId() {
        return subscriptionFilterId;
    }

    /**
     * Sets subscriptionFilterId.
     *
     * @param subscriptionFilterId New value for subscriptionFilterId.
     */
    public void setSubscriptionFilterId(long subscriptionFilterId) {
        this.subscriptionFilterId = subscriptionFilterId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof IotMessageRetained))
            return false;

        IotMessageRetained that = (IotMessageRetained)o;

        if (dateCreated != null ? !dateCreated.equals(that.dateCreated) : that.dateCreated != null)
            return false;

        if (dateModified != null ? !dateModified.equals(that.dateModified) : that.dateModified != null)
            return false;

        if (isActive != that.isActive)
            return false;

        if (id != that.id)
            return false;

        if (qos != that.qos)
            return false;

        if (partitionId != null ? !partitionId.equals(that.partitionId) : that.partitionId != null)
            return false;

        if (subscriptionFilterId != that.subscriptionFilterId)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = dateCreated != null ? dateCreated.hashCode() : 0;

        res = 31 * res + (dateModified != null ? dateModified.hashCode() : 0);

        res = 31 * res + (isActive ? 1 : 0);

        res = 31 * res + (int)(id ^ (id >>> 32));

        res = 31 * res + qos ;

        res = 31 * res + (partitionId != null ? partitionId.hashCode() : 0);

        res = 31 * res + (int)(subscriptionFilterId ^ (subscriptionFilterId >>> 32));

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "IotMessageRetained [dateCreated=" + dateCreated +
            ", dateModified=" + dateModified +
            ", isActive=" + isActive +
            ", id=" + id +
            ", partitionId=" + partitionId +
            ", subscriptionFilterId=" + subscriptionFilterId +
            "]";
    }
}

