/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.caricah.iotracah.bootstrap.data.models.subscriptions;

import java.io.*;
import java.util.Objects;

/**
 * IotSubscriptionKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 02/24/2016.
 */
public class IotSubscriptionKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;


    /** Value for partitionId. */
    private String partitionId;

    /** Value for clientId. */
    private String clientId;

    /** Value for subscriptionFilterId. */
    private long subscriptionFilterId;


    public String getPartitionId() {
        return partitionId;
    }

    public void setPartitionId(String partitionId) {
        this.partitionId = partitionId;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public long getSubscriptionFilterId() {
        return subscriptionFilterId;
    }

    public void setSubscriptionFilterId(long subscriptionFilterId) {
        this.subscriptionFilterId = subscriptionFilterId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof IotSubscriptionKey))
            return false;

        IotSubscriptionKey that = (IotSubscriptionKey)o;

        if (!Objects.equals(partitionId, that.partitionId))
            return false;
        if (!Objects.equals(clientId, that.clientId))
            return false;
        if (subscriptionFilterId != that.subscriptionFilterId)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {

        int res = 31 *  (clientId != null ? clientId.hashCode() : 0);

        res = 31 * res + (partitionId != null ? partitionId.hashCode() : 0);

        res = 31 * res + (int)(subscriptionFilterId ^ (subscriptionFilterId >>> 32));

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "IotSubscriptionKey [" +
                "partitionId=" + partitionId +
                ", clientId=" + clientId +
                ", subscriptionFilterId=" + subscriptionFilterId +
            "]";
    }
}

