#!/bin/sh
set -e

#
# This script is executed in the post-removal phase
#
#   On Debian,
#       $1=remove    : indicates a removal
#       $1=purge     : indicates an upgrade
#
#   On RedHat,
#       $1=0         : indicates a removal
#       $1=1         : indicates an upgrade



SOURCE_ENV_FILE=true
REMOVE_DIRS=false
REMOVE_SERVICE=false
REMOVE_USER_AND_GROUP=false

case "$1" in

    # Debian ####################################################
    remove)
        REMOVE_DIRS=true
        REMOVE_SERVICE=true
    ;;

    purge)
        REMOVE_USER_AND_GROUP=true
        SOURCE_ENV_FILE=false
    ;;
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade|disappear)
    ;;

    # RedHat ####################################################
    0)
        REMOVE_DIRS=true
        REMOVE_SERVICE=true
        REMOVE_USER_AND_GROUP=true
    ;;
    1)
        # If $1=1 this is an upgrade
        IS_UPGRADE=true
    ;;

    *)
        echo "post remove script called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Sets the default values for iotracah variables used in this script
IOT_USER="iotracah"
IOT_GROUP="iotracah"
LOG_DIR="/var/log/iotracah"
PLUGINS_DIR=""
PID_DIR="/var/run/iotracah"
DATA_DIR="/var/lib/iotracah"

# Source the default env file
if [ "$SOURCE_ENV_FILE" = "true" ]; then
    IOT_ENV_FILE="/etc/default/iotracah"
    if [ -f "$IOT_ENV_FILE" ]; then
        . "$IOT_ENV_FILE"
    fi
fi

if [ "$REMOVE_SERVICE" = "true" ]; then
    if command -v systemctl >/dev/null; then
        systemctl disable iotracah.service > /dev/null 2>&1 || true
    fi

    if command -v chkconfig >/dev/null; then
        chkconfig --del iotracah 2> /dev/null || true
    fi

    if command -v update-rc.d >/dev/null; then
        update-rc.d iotracah remove >/dev/null || true
    fi
fi

if [ "$REMOVE_DIRS" = "true" ]; then

    if [ -d "$LOG_DIR" ]; then
        echo -n "Deleting log directory..."
        rm -rf "$LOG_DIR"
        echo " OK"
    fi

    if [ -d "$PLUGINS_DIR" ]; then
        echo -n "Deleting plugins directory..."
        rm -rf "$PLUGINS_DIR"
        echo " OK"
    fi

    if [ -d "$PID_DIR" ]; then
        echo -n "Deleting PID directory..."
        rm -rf "$PID_DIR"
        echo " OK"
    fi

    # Delete the data directory if and only if empty
    if [ -d "$DATA_DIR" ]; then
        rmdir --ignore-fail-on-non-empty "$DATA_DIR"
    fi
fi

if [ "$REMOVE_USER_AND_GROUP" = "true" ]; then
    if id "$IOT_USER" > /dev/null 2>&1 ; then
        userdel "$IOT_USER"
    fi

    if getent group "$IOT_GROUP" > /dev/null 2>&1 ; then
        groupdel "$IOT_GROUP"
    fi
fi

exit 0
# Built for iotracah
