#!/bin/sh
set -e

#
# This script is executed in the pre-installation phase
#
#   On Debian,
#       $1=install : indicates an new install
#       $1=upgrade : indicates an upgrade
#
#   On RedHat,
#       $1=1       : indicates an new install
#       $1=2       : indicates an upgrade



# Sets the default values for iotracah variables used in this script
IOT_USER="iotracah"
IOT_GROUP="iotracah"

# Source the default env file
IOT_ENV_FILE="/etc/default/iotracah"
if [ -f "$IOT_ENV_FILE" ]; then
    . "$IOT_ENV_FILE"
fi

case "$1" in

    # Debian ####################################################
    install|upgrade)

        # Create iotracah group if not existing
        if ! getent group "$IOT_GROUP" > /dev/null 2>&1 ; then
            echo -n "Creating $IOT_GROUP group..."
            addgroup --quiet --system "$IOT_GROUP"
            echo " OK"
        fi

        # Create iotracah user if not existing
        if ! id $IOT_USER > /dev/null 2>&1 ; then
            echo -n "Creating $IOT_USER user..."
            adduser --quiet \
                    --system \
                    --no-create-home \
                    --ingroup "$IOT_GROUP" \
                    --disabled-password \
                    --shell /bin/false \
                    "$IOT_USER"
            echo " OK"
        fi
    ;;
    abort-deconfigure|abort-upgrade|abort-remove)
    ;;

    # RedHat ####################################################
    1|2)

        # Create iotracah group if not existing
        if ! getent group "$IOT_GROUP" > /dev/null 2>&1 ; then
            echo -n "Creating $IOT_GROUP group..."
            groupadd -r "$IOT_GROUP"
            echo " OK"
        fi

        # Create iotracah user if not existing
        if ! id $IOT_USER > /dev/null 2>&1 ; then
            echo -n "Creating $IOT_USER user..."
            useradd --system \
                    -M \
                    --gid "$IOT_GROUP" \
                    --shell /sbin/nologin \
                    --comment "iotracah user" \
                    "$IOT_USER"
            echo " OK"
        fi
    ;;

    *)
        echo "pre install script called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
# Built for iotracah
