/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.caricah.iotracah.bootstrap.data.models.client;

import java.io.*;

/**
 * IotClientKey definition.
 *
 * Code generated by Apache Ignite Schema Import utility: 02/24/2016.
 */
public class IotClientKey implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /** Value for sessionId. */
    private String sessionId;

    /**
     * Gets sessionId.
     *
     * @return Value for sessionId.
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets sessionId.
     *
     * @param sessionId New value for sessionId.
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /** {@inheritDoc} */
    @Override public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof IotClientKey))
            return false;

        IotClientKey that = (IotClientKey)o;

        if (sessionId != null ? !sessionId.equals(that.sessionId) : that.sessionId != null)
            return false;

        return true;
    }

    /** {@inheritDoc} */
    @Override public int hashCode() {
        int res = sessionId != null ? sessionId.hashCode() : 0;

        return res;
    }

    /** {@inheritDoc} */
    @Override public String toString() {
        return "IotClientKey [sessionId=" + sessionId +
            "]";
    }
}

